alias bunx 'vpx'
alias c 'clear'
alias code 'vim'
alias grep 'grep --color=auto --exclude-dir={.bzr,CVS,.git,.hg,.svn,.idea,.tox}'
alias la 'eza -la --icons --git'
alias ll 'eza -l --icons --git'
alias ls 'eza'
alias npx 'vpx'
alias pbc 'pbcopy'
alias pbp 'pbpaste'
alias pn 'pnpm'
alias scratch 'nvim -c "setlocal buftype=nofile"'
alias vimdiff 'nvim -d'
alias wr 'wrangler'
